kanji_dict = {
    "一": ["one", [["ichi"], "itsu", "hito", "hito-tsu"]],
    "二": ["two", [["ni"], "futa", "futa-tsu"]],
    "三": ["three", [["san"], "mi", "mi-tsu", "mi'-tsu"]],
    "四": ["four", [["shi"], "yo", "yo-tsu", "yo'-tsu", "yon"]],
    "五": ["five", ["go", ["itsu"], "itsu-tsu"]],
    "六": ["six", [["roku"], "mu", "mu-tsu", "mu'-tsu", "(mui)"]],
'七': ['seven', 'shichi'],
    '八': ['eight', 'hachi'],
    '九': ['nine', 'kyuu'],
    '十': ['ten', 'juu'],
    '百': ['hundred', 'hyaku'],
    '千': ['thousand', 'sen'],
    '万': ['ten thousand', 'man'],
    '円': ['yen', 'en'],
    '年': ['year', 'nen'],
    '月': ['month', 'gatsu'],
    '日': ['day', 'nichi'],
    '時': ['hour', 'ji'],
    '分': ['minute', 'fun'],
    '秒': ['second', 'byou'],
    '本': ['book', 'hon'],
    '人': ['person', 'jin'],
    '学': ['study', 'gaku'],
    '校': ['school', 'kou'],
    '先': ['before', 'saki'],
    '生': ['life', 'sei'],
    '亜': ['a', 'a'],
    '哀': ['pathetic', 'aware'],
    '挨': ['push open', 'ai'],
    '愛': ['love', 'ai'],
    '曖': ['not clear', 'ai'],
    '淫': ['lewdness', 'in'],
    '王': ['king', 'ou'],
    '火': ['fire', 'hi'],
    "海": ["sea", ["umi*^", "kai"]],
    '夢': ['dream', 'yume'],
    '玉': ['ball', 'tama'],
    '鶏': ['chicken', 'niwatori'],
    '心': ['heart', 'kokoro'],
    '田': ['rice field', 'ta'],
    '口': ['mouth', 'kuchi'],
    '工': ['craft', 'kō'],
    '木': ['tree', 'ki'],
    '樹': ['mature tree', 'ju'],
    '水': ['water', 'mizu'],
    '神': ['god', 'kami'],
    '目': ['eye', 'me'],
    '門': ['gate', 'mon'],
    '紋': ['family crest', 'mon'],
    '大': ['large', 'dai'],
    '阜': ['mound', 'fu'],
    '米': ['rice', 'kome'],
    '手': ['hand', 'te'],
    '鳥': ['bird', 'tori'],
    '言': ['speech', 'gen'],
    "疾": ["rapid", ["shitsu", "hayai*^"]],
    '嫉': ['envy', 'shitsu'],
    '芝': ['turf', 'shiba'],
    '車': ['car', 'kuruma'],
    '悪': ['bad', 'aku'],
    '善': ['good', 'zen'],
    '毀': ['ruin', 'ki'],
    '滅': ['eradication', 'metsu'],
    '消': ['extinguish', "shō"],
    '圧': ['pressure', 'atsu'],
    '嵐': ['storm', 'arashi'],
    '山': ['mountain', 'yama'],
    '医': ['doctor', 'i'],
    '意': ['idea', 'i'],
    '犬': ['dog', 'inu'],
    '死': ['death', 'shi'],
    '食': ['eat', 'taberu'],
    '糸': ['thread', 'ito'],
    '氷': ['ice', 'koori'],
    '雨': ['rain', 'ame'],
    '色': ['color', 'iro'],
    '植': ['plant', 'ueru'],
    '芋': ['potato', 'imo'],
    '鬱': ['gloom', 'utsu'],
    '雲': ['cloud', 'kumo'],
    '永': ['eternity', 'nagai'],
    '蚊': ['mosquito', 'ka'],
    '肉': ['meat', 'niku'],
    '非': ['negative', 'hi'],
    '猫': ['cat', 'neko'],
    '賓': ['visitor', 'hin'],
    '父': ['father', 'chichi'],
    '福': ['luck', 'fuku'],
    '幣': ['money', 'hei'], #tai
    '弊': ['abuse', 'hei'],
    '遍': ['everywhere', 'hen'],
    '衣': ['clothes', 'koromo'],
    '衷': ['inmost', 'chū'],
    '裸': ['naked', 'hadaka'],
    '闇': ['darkness', 'yami'],
    '哲': ['philosophy', 'tetsu'],
    '天': ['heaven', 'ten'],
    '土': ['soil', 'tsuchi'],
    '刀': ['sword', 'katana'],
    '皿': ['dish', 'sara'],
    '象': ['elephant', 'zō'],
    '獣': ['animal', 'kemono'],
    '干': ['airing', 'hosu'],
    '乾': ['dry', 'kan'],
    '畏': ['fear', 'osoreru'],
    '危': ['dangerous', 'abunai'],
    '利': ['profit', 'ri'],
    '果': ['fruit', 'ka'],
    '家': ['house', 'ie'],
    '竜': ['dragon', 'ryū'],
    '卵': ['egg', 'tamago'],
    '媛': ['princess', 'hime'],
    '凹': ['concave', 'ō'],
    '乙': ['the latter', 'otsu'],
    '私': ['me', 'watashi'], 
    '君': ['you', 'kimi'],
    '詐': ['lie', 'sa'],
    '実': ['truth', 'jitsu'],
    '真': ['true', 'shin'],
    '間': ['interval', 'aida'],
    '閲': ['review', 'etsu'],
    '開': ['open', 'kai'],
    '援': ['give assistance', 'en'],
    '扶': ['physical support', 'fu'],
    '荒': ['laid waste', 'kō'],
    '佐': ['assistant', 'sa'],
    '助': ['help', 'suke'],
    '尚': ['esteem', 'shō'],
    '子': ['child in general', 'ko'],
    '児': ['child', 'ji'],
    '幼': ['infancy', 'osanai'],
    '維': ['fiber', 'i'],
    '遺': ['bequeath', 'i'],
    '茨': ['thorn', 'ibara'],
    '逸': ['deviate', 'itsu'],
    '晶': ['sparkle', 'shō'],
    '悲': ['sadness', 'kanashii'],
    '情': ['feelings', 'jō'],
    '霊': ['spirit', 'rei'],
    '魂': ['soul', 'tamashii'],
    '針': ['needle', 'hari'],
    '蛇': ['snake', 'hebi'],
    '毒': ['poison', 'doku'],
    '仲': ['relationship', 'naka'],
    '界': ['world', 'kai'],
    '世': ['human society', 'yo'],
    '骸': ['corpse', 'mukuro'],
    '中': ['middle', 'naka'],
    '虫': ['insect', 'mushi'],
    '町': ['town', 'machi'],
    '強': ['strong', 'tsuyoi'],
    '鼻': ['nose', 'hana'],
    '友': ['friend', 'tomo'],
    '敵': ['enemy', 'teki'],
    '猟': ['hunting', 'ryō'],
    "胃": ["stomach", "i"],
    "尻": ["buttock", "shiri"],
    "芯": ["core", "shin"],
    "味": ["flavor", "aji"],
    "矛": ["halberd", "hoko"],
    "無": ["nothingness", "mu"],
    "霧": ["fog", "kiri"],
    "娘": ["daughter", "musume"],
    "名": ["name", "na"],
    "命": ["fate", "inochi"],
    "破": ["rend", "ha"],
    "壊": ["demolition", "kai"],
    "魚": ["fish", "sakana"],
    "鯨": ["whale", "kujira"],
    "倹": ["frugal", "ken"],
    "健": ["healthy", "ken"],
    "賢": ["intelligent", "ken"],
    "拘": ["arrest", "kō"],
    "侯": ["marquis", "kō"],
    "丈": ["length", "jō"],
    "腕": ["arm", "ude"],
    "湾": ["gulf", "wan"],
    "話": ["talk", "hanashi"],
    "麓": ["mountain base", "fumoto"],
    "齢": ["age", "toshi"],
    "呂": ["spine", "ro"],
    "錬": ["tempering", "ren"],
    "胸": ["bosom", "mune"],
    "亀": ["turtle", "kame"],
    "騎": ["equestrian", "ki"],
    "吉": ["good luck", "kichi"],
    "却": ["instead", "kyaku"],
    "久": ["long time", "kyū"],
    "譜": ["musical score", "fu"],
    "副": ["vice", "fuku"],
    "仏": ["buddha", "butsu"],
    "物": ["thing", "mono"],
    "粉": ["flour", "kon"],
    "雰": ["atmosphere", "fun"],
    "墳": ["tomb", "fun"],
    "文": ["writing", "bun"],
    "丙": ["third class", "hei"],
    "平": ["flat", "hei"],
    "風": ["wind", "fū"],
    "終": ["end", "shū"],
    "末": ["end of something", "matsu"],
    "了": ["finish", "ryō"],
    "端": ["edge", "hashi"],
    "幸": ["happiness", "kō"],
    "竹": ["bamboo", "take"],
    "見": ["see", "ken"],
    "椅": ["chair", "i"],
    "同": ["same", "onaji"],
    "委": ["committee", "i"],
    "尉": ["military officer", "i"],
    "引": ["pull", "hiku"],
    "因": ["cause", "in"],
    "咽": ["throat", "in"],
    "曜": ["day of the week", "yō"],
    "金": ["gold", "kane"],
    "殺": ["kill", "koro-su"],
    "女": ["woman", "onna"],
    "美": ["beauty", "utsuku-shii"],
    "妊": ["pregnancy", "nin"],
    "獄": ["prison", "goku"],
    "鬼": ["demon", "oni"],
    "赤": ["red", "aka"],
    "石": ["stone", "ishi"],
    "夕": ["evening", "yū"],
    "首": ["neck", "kubi"],
    "準": ["standard", "jun"],
    "譲": ["defer", "yuzu-ru"],
    "標": ["signpost", "hyō"],
    "部": ["part", "bu"],
    "星": ["star", "hoshi"],
    "陽": ["sunshine", "yō"],
    "飲": ["drink", "no-mu"],
    "酒": ["alcoholic drink", "sake"],
    "欺": ["deceit", "gi"],
    "眠": ["sleep", "nemu-ru"],
    "黒": ["black", "kuro"],
    "花": ["flower", "hana"],
    "瓶": ["flower pot", "bin"],
    "羽": ["feather", "hane"],
    "奏": ["play music", "sō"],
    "等": ["class", "tō"], 
    "壁": ["wall", "kabe"],
    "握": ["grip", "nigi-ru"],
    "礼": ["thanks", "rei"],
    "冷": ["cool", "rei"],
    "隷": ["slave", "rei"],
    "川": ["river", "kawa"],
    "河": ["literary river", "kawa"],
    "足": ["foot", "ashi"],
    "脅": ["threaten", "odosu"],
    "牛": ["cow", "ushi"],
    "去": ["leave", "sa-ru"],
    "嫁": ["marry into", "yome"],
    "明": ["bright", "aka-rui"],
    "尺": ["shaku", "shaku"],
    "出": ["exit", "de-ru"],
    "小": ["small", "chii-sai"],
    "傷": ["wound", "kizu"],
    "写": ["copy", "utsu-su"],
    "複": ["duplicate", "fuku"],
    "扱": ["handle", "atsuka-u"],
    "囲": ["surround", "kako-mu"],
    "右": ["right", "migi"],
    "左": ["left", "hidari"],
    "斎": ["purification", "sai"],
    "呪": ["curse", "noroi"],
    "立": ["stand up", "ta-tsu"],
    "在": ["exist", "zai"],
    "己": ["self", "onore"],
    "粒": ["grains", "tsubu"],
    "魔": ["witch", "ma"],
    "叱": ["scold", ["shitsu", "shika-ru",["shika"]]],
    "誤": ["mistake", "go"],
    "侍": ["samurai", "samurai"],
    "黄": ["yellow", "kō"],
    "絵": ["picture", "e"],
    "怪": ["suspicious", "kai"],
    "悔": ["repent", "ku-yamu"],
    "母": ["mother", "haha"],
    "姉": ["older sister", "ane"],
    "妹": ["younger sister", "imōto"],
    "兄": ["older brother", "ani"],
    "弟": ["younger brother", "otōto"],
    "化": ["change", "ka"],
    "変": ["strange change", "hen"],
    "艦": ["warship", "kan"],
    "炎": ["inflammation", "en"],
    "欧": ["europe", "ō"],
    "桜": ["cherry tree", "sakura"],
    "快": ["cheerful", "kai"],
    "角": ["angle", "kaku"],
    "柳": ["willow", "yanagi"],
    "唆": ["tempt", "sa"],
    "読": ["read", "yo-mu"],
    "栃": ["horse chestnut", "tochi"],
    "凸": ["convex", "totsu"],
    "愉": ["pleasure", "yu"],
    "楽": ["activity enjoyment", "raku"],
    "修": ["discipline cultivation", "shū"],
    "培": ["nurturing cultivation", "bai"],
    "育": ["nurture living things", "iku"],
    "挙": ["lift", "a-geru"],
    "沙": ["poetic sand", "sa"],
    "砂": ["sand", "suna"],
    "蚕": ["silkworm", "ka"],
    "璽": ["emperor's seal", "ji"],
    "皇": ["emperor", "kō"],
    "漂": ["drift", "tadayo-u"],
    "梅": ["ume apricot", "ume"],
    "陪": ["obeisance or serve", "bai"],
    "藻": ["seaweed", "mo"],
    "島": ["island", "shima"],
    "討": ["chastise", "tō"],
    "刑": ["punish", "kei"],
    #"戒"
    "道": ["path", [["dō"], "(tō)", "michi"]],
    "路": ["road", ["ro", "ji"]],
    "街": ["town streets or activity", ["gai", "(kai)", "machi"]],
    #"捗": [""]
    "憎": ["hate", ["zō", "niku-mu", "niku-i", "niku-rashii", "niku-shimi"]],
    "則": ["rule", ["soku"]],
    "乳": ["milk", ["nyū", "chichi", "chi"]],
    "偶": ["by chance", "gū"],
    "語": ["language", [["go"], "kata-ru", "kata-rau"]],
    "夜": ["night", ["ya", "yo", ["yoru"]]],
    "朝": ["morning or new rise", ["chō", ["asa"], "ten"]],
    "弐": ["financial two", ["ni"]],
    "守": ["protect", ["shu", "(su)", ["mamo-ru"], "mo-ri", "mamori"]],
    "如": ["likeness", ["jo", "nyo", ["gotoku"]]],
    "豆": ["bean", ["tō", "(zu)", ["mame"]]],
    "信": ["trust or signal or spiral", [["shin"], "nobu", "makoto", "uzumaki"]],
    "頼": ["trust or reliance", [["tayori"], "rai", "tano-mu", "tano-moshii", "tayo-ru"]],
    "希": ["hope or rare", [["ki"], "nozomu", "nozomi", "mezurashii"]],
    "望": ["hope or envision", ["bō", ["mō"], "nozo-mu"]],
    "忘": ["forget", ["bō", ["wasu-reru"], "mou", "bouru"]],
    "益": ["benefit", [["eki"], "(yaku)", "masu", "masaru"]],
    "理": ["reason", [["ri"], "kotowari", "kagaku", "seiri", "shinri"]],
    "由": ["motive", ["yu", "yū", "(yui)", ["yoshi"], "minamoto"]],
    #"載": [""]
    "憧": ["desire", ["shō", "akoga-reru", ["akogare"]]],
    "寺": ["buddhist temple", ["ji", ["tera"]]],
    "歌": ["song", ["ka", ["uta"], "uta-u"]],
    "字": ["letter", ["ji", ["aza"], "shi", "aza-na"]],
    "墜": ["crash", [["tsui"], "otsu"]],
    "宜": ["best regards", [["gi"], "yoroshiku", "yoroshii"]],
    "湖": ["lake", [["ko"], "mizūmi"]],
    "奇": ["unusual", [["ki"], "omoshiroi", "ku"]],
    "犠": ["sacrifice", [["gi"], "ikenie"]],
    "醒": ["disillusioned or sober", ["sei", "same", ["sameru"], "sameshimeru"]], # verify most common
    "働": ["work", ["dō", ["hatara-ku"]]],
    "紛": ["distract", [["fun"], "magi-reru", "magi-rasu", "magi-rawasu", "magi-rawashii", "fuu"]],
    "勉": ["exert", ["ben"]],
    "少": ["few", ["shō", ["suku-nai"], "suko-shi", "suko", "suku"]],
    "醜": ["ugly", ["shū", ["miniku-i"]]],
    "髪": ["head hair", ["hatsu", ["kami"]]],
    "毛": ["hair or fur", ["mō", ["ke"]]],
    "不": ["non-", [["fu"], "bu"]],
    "嫌": ["dislike", ["ken", "(gen)", "kira-u", ["iya"]]],
    "疑": ["doubt", [["gi"], "utaga-u"]],
    "鎖": ["chain", ["sa", ["kusari"]]],
    "受": ["accept", ["ju", ["u-keru"], "u-karu", "shu", "uke"]],
    "喪": ["miss", [["sō"], "mo^", "ushina", "ou"]],
    "過": ["go beyond", [["ka^"], "su-giru", "su-gosu", "ayama-tsu", "ayama-chi", "sugi", "ayama"]],
    "痛": ["pain", ["tsū^", ["ita-i"], "ita-mu", "ita-meru", "tsu^"]],
    "送": ["send", ["sō", ["oku-ru"], "oku"]],
    "還": ["return or still", ["kan", "kaeru*^"]],
    "律": ["law or music scale", ["ritsu*^", "(richi)", "osameru", "osamaru", "nori"]],
    "享": ["receive", ["kyō*", "toshirau"]],
    "室": ["room", ["shitsu*^", "muro"]],
    "森": ["forest", ["shin", "mori*^"]],
    "曲": ["music or curve", ["kyoku*^", "ma-garu", "ma-geru", "magari", "kuse"]],
    "湿": ["damp", ["shitsu*^", "shime-ru", "shime-su"]],
    "泣": ["cry", ["kyū", "na-ku*^"]],
    "忍": ["endure or hide", ["nin*^", "shino-bu", "shino-baseru"]],
    "術": ["art", ["jutsu*^", "sube", "suji"]],
    "衰": ["decline", ["sui*", "otoro-eru^", "otoroshii"]],
    "損": ["loss", ["son*^", "soko-nau", "soko-neru"]],
    "国": ["country", ["koku*", "kuni^", "shiku", "shuu", "furusato", "tami"]],
    "息": ["breath or concern", ["soku", "iki*^", "okonau"]],
    "付": ["attach", ["fu*^", "tsu-keru", "tsu-ku", "tsuke"]],
    "待": ["wait", ["tai", "ma-tsu*^", "machi"]],
    "制": ["system control", ["sei*^", "sei-suru", "sei-zuru"]],
    "轄": ["jurisdiction", ["katsu*^", "gak", "fusegu", "makaseru"]],
    "虚": ["void", ["kyo*^", "(ko)", "utsuro", "kara", "kyo"]],
    "宛": ["address or depend on", ["a-teru", "ate*^", "yoru"]],
    "旅": ["trip", ["ryo", "tabi*^"]]
    
    #12
    }
    #"軽"
    #闘
    #起
    
    